[build]
  builder = "nixpacks"
  buildCommand = "pnpm install && pnpm run build"

[deploy]
  startCommand = "npm run preview"
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 10

[[services]]
  name = "toefl-game-frontend"

[env]
  NODE_VERSION = "20"
